### ISSUE TITLE
[BUG] Content Blocks Field in type: Collection are not translated

### ISSUE THREAD

**Issue by andrekoller** [web-vision/deepltranslate-core#439]
Content Blocks Field in type: Collection are not translated

my configuration:

`fields:
  -
    identifier: header
    useExistingField: true
    label: Titel
  - identifier: boxes
    label: Boxes
    type: Collection
    labelField: title
    maxitems: 12
    minitems: 1
    appearance:
      collapseAll: true
      levelLinksPosition: both
    fields:
      - identifier: title
        type: Text
        label: Titel
        required: true
      - identifier: text
        type: Textarea
        label: Teaser-Text
 `

header ist translated.
title and text in collection are not translated

**Comment by calien666** [comment]
I guess, the issue would be, the override for the fields setting the `l10n_mode` to `prefixLangTitle` is not done. I guess, this would help.

Try, if your adjusted setting will fix the issue:
```yaml
fields:
  -
    identifier: header
    useExistingField: true
    label: Titel
  - identifier: boxes
    label: Boxes
    type: Collection
    labelField: title
    maxitems: 12
    minitems: 1
    appearance:
      collapseAll: true
      levelLinksPosition: both
    fields:
      - identifier: title
        type: Text
        label: Titel
        l10n_mode: prefixLangTitle
        required: true
      - identifier: text
        type: Textarea
        l10n_mode: prefixLangTitle
        label: Teaser-Text
```
